Ugh. Bad rebase.
animate-object/is-ten pull request #2
Opened 2019-06-07 15:54 UTC by mattsp1290

Copy-paste to fix previous copy-paste

2019-06-08 16:05 UTC, animate-object requested changes
looks like a great start! please address pull request comments and we can get this through

2019-06-08 16:05 UTC, animate-object commented on package-lock.json
> +{
excellent, it will be good to have both a `package-lock.json` and a `yarn.lock`

2019-06-08 16:05 UTC, animate-object commented on package.json
>    }
don't forget to add your name to the contributors field, so you are forever associated with this project.

2019-06-08 16:05 UTC, animate-object commented on index.js
> +  return jQuery.equals(val, 10);
```suggestion
  return jQuery.equals(jQuery.divide(val, jQuery.ten), jQuery.one);
```

https://github.com/cbrandolino/jQuery-basic-arithmetic-plugin/blob/master/jquery.basic_arithmetics.js#L94

2019-06-11 15:13 UTC, mattsp1290 commented
@animate-object  Made changes requested. Not sure why, but jQuery.ten and jQuery.one are undefined.

2019-06-13 03:27 UTC, animate-object approved these changes
really nice work on this. it does what it did before, but with jquery. wow!

2019-06-13 03:27 UTC, merged